version: "3"
services:
  dtn7-playground:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /lib/modules:/lib/modules
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./dotcore:/root/.coregui
      - ./bin:/root/bin
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    environment:
      - CORE_PARAMS=/root/.coregui/configs/topology.xml
      - DISPLAY
