version: "3"
services:
    core:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./dotcore:/root/.core
            - ./utils:/utils
            - ./experiment.py:/root/experiment.py
            - ./results:/results
        privileged: true
        env_file:
            - experiment_settings.env
        environment:
            - DISPLAY