# SPDX-FileCopyrightText: 2021 Jonas Höchst
# SPDX-FileCopyrightText: 2021 Artur Sterz
# SPDX-FileCopyrightText: 2021, 2022 Alvar Penning
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Deadlock Experiment Testing

on: repository_dispatch

jobs:
  core:
    name: Run CORE experiments

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runtime: [60, 600]
        bundles_per_node: [1, 600]
        payload_size: [1000, 1000000]
    container:
      image: maciresearch/core_worker:7.5.1-1
      options: --privileged
      volumes:
        - /lib/modules/:/lib/modules/

    steps:
    - name: Install additional dependencies
      run: |
        apt-get update
        apt-get install -y nodejs psmisc git

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18'

    - name: Checkout repo with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build and Install dtn7
      run: |
        cd dtn7-go
        git checkout master
        git pull
        git describe
        go build ./cmd/dtn-tool
        install dtn-tool /usr/local/bin/
        go build ./cmd/dtnd
        install dtnd /usr/local/bin

    - name: Link dotcore and bin files
      run: |
        ln -s $PWD/dotcore /root/.core
        echo "$PWD/bin" >> $GITHUB_PATH

    - name: Run experiment
      id: experiment
      continue-on-error: true
      env:
        EXPERIMENT_RUNTIME: ${{ matrix.runtime }}
        BUNDLES_PER_NODE: ${{ matrix.bundles_per_node }}
        PAYLOAD_SIZE: ${{ matrix.payload_size }}
      run: |
        python3 /root/.core/experiments/deadlock.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: logfiles
        path: |
          /tmp/results/

    - name: Check failures
      if: steps.experiment.outcome != 'success'
      run: exit 1
